export const scoringPolicy = {
  version: "1.0",
  privacy_scoring_framework: {
    max_score: 100,
    categories: {
      data_collection: {
        max_deduction: 25,
        weights: {
          collects_email: -1,
          collects_phone_number: -2,
          tracks_precise_location: -5,
          accesses_contact_list: -5,
          collects_photos_videos: -3,
          collects_biometrics: -10,
          collects_health_data: -10,
          collects_financial_data: -5,
          uses_device_fingerprinting: -7,
        },
      },
      data_sharing: {
        max_deduction: 30,
        weights: {
          shares_with_affiliates: -3,
          shares_with_analytics_providers: -3,
          shares_with_advertisers: -10,
          sells_user_data: -20,
          shares_sensitive_data: -20,
          unrestricted_third_party_sharing: -15,
        },
      },
      user_rights: {
        max_bonus: 15,
        weights: {
          account_deletion_available: 3,
          data_export_available: 3,
          data_correction_available: 2,
          consent_withdrawal_available: 3,
          right_to_object_available: 2,
          child_privacy_protections: 2,
        },
      },
      data_retention: {
        weights: {
          less_than_6_months: 2,
          less_than_12_months: 1,
          between_1_and_3_years: 0,
          between_3_and_5_years: -2,
          more_than_5_years: -5,
          indefinite: -10,
        } as Record<string, number>,
      },
      tracking_surveillance: {
        max_deduction: 10,
        weights: {
          cookies_only: -1,
          behavioral_profiling: -3,
          cross_site_tracking: -5,
          advertising_tracking: -4,
          session_replay: -5,
          device_fingerprinting: -7,
        },
      },
      legal_fairness: {
        max_deduction: 10,
        weights: {
          forced_arbitration: -4,
          class_action_waiver: -3,
          broad_liability_waiver: -3,
          unilateral_terms_changes: -2,
          perpetual_content_license: -5,
        },
      },
      security_practices: {
        max_bonus: 10,
        weights: {
          encryption_at_rest: 2,
          encryption_in_transit: 2,
          soc2_certification: 2,
          iso_27001_certification: 2,
          bug_bounty_program: 2,
        },
      },
    },
  },
  grade_mapping: {
    "A+": { min: 90, max: 100 },
    A: { min: 85, max: 89 },
    "A-": { min: 80, max: 84 },
    "B+": { min: 75, max: 79 },
    B: { min: 70, max: 74 },
    "B-": { min: 65, max: 69 },
    "C+": { min: 60, max: 64 },
    C: { min: 55, max: 59 },
    "C-": { min: 50, max: 54 },
    D: { min: 40, max: 49 },
    F: { min: 0, max: 39 },
  } as Record<string, { min: number; max: number }>,
  data_sensitivity_score: {
    max_weight: 140,
    weights: {
      email: 5,
      phone: 10,
      location: 15,
      contacts: 20,
      financial: 25,
      health: 30,
      biometrics: 35,
    },
    risk_levels: {
      low: { min: 0, max: 20 },
      moderate: { min: 21, max: 40 },
      elevated: { min: 41, max: 60 },
      high: { min: 61, max: 80 },
      critical: { min: 81, max: 100 },
    },
  },
  transparency_score: {
    max_score: 100,
    criteria: {
      policy_readability: 20,
      retention_disclosed: 20,
      data_sharing_disclosed: 20,
      user_rights_explained: 20,
      security_practices_disclosed: 20,
    },
  },
  flag_rules: {
    red_flags: [
      "sells_user_data",
      "collects_biometrics",
      "indefinite_retention",
      "forced_arbitration",
      "shares_with_advertisers",
      "cross_site_tracking",
      "device_fingerprinting",
      "perpetual_content_license",
    ],
    amber_flags: [
      "tracks_precise_location",
      "shares_with_analytics_providers",
      "long_term_retention",
      "behavioral_profiling",
      "class_action_waiver",
      "unilateral_terms_changes",
    ],
    green_flags: [
      "account_deletion_available",
      "data_export_available",
      "gdpr_compliant",
      "ccpa_compliant",
      "encryption_at_rest",
      "encryption_in_transit",
      "short_retention_period",
      "does_not_sell_data",
    ],
  },
} as const;
